//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 01:36:44 AM CST 
//


package org.f3tools.incredible.smartETL.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.f3tools.incredible.smartETL.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.f3tools.incredible.smartETL.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLLookup }
     * 
     */
    public XMLLookup createXMLLookup() {
        return new XMLLookup();
    }

    /**
     * Create an instance of {@link SmartTransStepDef }
     * 
     */
    public SmartTransStepDef createSmartTransStepDef() {
        return new SmartTransStepDef();
    }

    /**
     * Create an instance of {@link SmartTransStepDef.Filter }
     * 
     */
    public SmartTransStepDef.Filter createSmartTransStepDefFilter() {
        return new SmartTransStepDef.Filter();
    }

    /**
     * Create an instance of {@link SmartTransStepDef.Mappings }
     * 
     */
    public SmartTransStepDef.Mappings createSmartTransStepDefMappings() {
        return new SmartTransStepDef.Mappings();
    }

    /**
     * Create an instance of {@link SmartTransStepDef.Mappings.Mapping }
     * 
     */
    public SmartTransStepDef.Mappings.Mapping createSmartTransStepDefMappingsMapping() {
        return new SmartTransStepDef.Mappings.Mapping();
    }

    /**
     * Create an instance of {@link SmartTransStepDef.Variables }
     * 
     */
    public SmartTransStepDef.Variables createSmartTransStepDefVariables() {
        return new SmartTransStepDef.Variables();
    }

    /**
     * Create an instance of {@link XMLDataDef }
     * 
     */
    public XMLDataDef createXMLDataDef() {
        return new XMLDataDef();
    }

    /**
     * Create an instance of {@link XMLJob }
     * 
     */
    public XMLJob createXMLJob() {
        return new XMLJob();
    }

    /**
     * Create an instance of {@link StepDef }
     * 
     */
    public StepDef createStepDef() {
        return new StepDef();
    }

    /**
     * Create an instance of {@link XMLLookup.Database }
     * 
     */
    public XMLLookup.Database createXMLLookupDatabase() {
        return new XMLLookup.Database();
    }

    /**
     * Create an instance of {@link XMLLookup.File }
     * 
     */
    public XMLLookup.File createXMLLookupFile() {
        return new XMLLookup.File();
    }

    /**
     * Create an instance of {@link XMLLookup.Keys }
     * 
     */
    public XMLLookup.Keys createXMLLookupKeys() {
        return new XMLLookup.Keys();
    }

    /**
     * Create an instance of {@link XMLLookup.Values }
     * 
     */
    public XMLLookup.Values createXMLLookupValues() {
        return new XMLLookup.Values();
    }

    /**
     * Create an instance of {@link SmartTransStepDef.Externalprocess }
     * 
     */
    public SmartTransStepDef.Externalprocess createSmartTransStepDefExternalprocess() {
        return new SmartTransStepDef.Externalprocess();
    }

    /**
     * Create an instance of {@link SmartTransStepDef.Filter.Formula }
     * 
     */
    public SmartTransStepDef.Filter.Formula createSmartTransStepDefFilterFormula() {
        return new SmartTransStepDef.Filter.Formula();
    }

    /**
     * Create an instance of {@link SmartTransStepDef.Mappings.Mapping.Formula }
     * 
     */
    public SmartTransStepDef.Mappings.Mapping.Formula createSmartTransStepDefMappingsMappingFormula() {
        return new SmartTransStepDef.Mappings.Mapping.Formula();
    }

    /**
     * Create an instance of {@link SmartTransStepDef.Variables.Variable }
     * 
     */
    public SmartTransStepDef.Variables.Variable createSmartTransStepDefVariablesVariable() {
        return new SmartTransStepDef.Variables.Variable();
    }

    /**
     * Create an instance of {@link XMLDataDef.Field }
     * 
     */
    public XMLDataDef.Field createXMLDataDefField() {
        return new XMLDataDef.Field();
    }

    /**
     * Create an instance of {@link XMLDataDef.Excludes }
     * 
     */
    public XMLDataDef.Excludes createXMLDataDefExcludes() {
        return new XMLDataDef.Excludes();
    }

    /**
     * Create an instance of {@link XMLJob.Property }
     * 
     */
    public XMLJob.Property createXMLJobProperty() {
        return new XMLJob.Property();
    }

    /**
     * Create an instance of {@link XMLJob.Flow }
     * 
     */
    public XMLJob.Flow createXMLJobFlow() {
        return new XMLJob.Flow();
    }

}
