//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 01:36:44 AM CST 
//


package org.f3tools.incredible.smartETL.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lookup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lookup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datadef" type="{}datadef"/>
 *         &lt;element name="inmemory" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sourcetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="database" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="sql" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="loadall" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="file" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="delimiter" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="quote" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="keys">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="values">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lookup", propOrder = {
    "name",
    "datadef",
    "inmemory",
    "sourcetype",
    "database",
    "file",
    "keys",
    "values"
})
public class XMLLookup {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected XMLDataDef datadef;
    protected boolean inmemory;
    @XmlElement(required = true)
    protected String sourcetype;
    protected XMLLookup.Database database;
    protected XMLLookup.File file;
    @XmlElement(required = true)
    protected XMLLookup.Keys keys;
    @XmlElement(required = true)
    protected XMLLookup.Values values;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the datadef property.
     * 
     * @return
     *     possible object is
     *     {@link XMLDataDef }
     *     
     */
    public XMLDataDef getDatadef() {
        return datadef;
    }

    /**
     * Sets the value of the datadef property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLDataDef }
     *     
     */
    public void setDatadef(XMLDataDef value) {
        this.datadef = value;
    }

    /**
     * Gets the value of the inmemory property.
     * 
     */
    public boolean isInmemory() {
        return inmemory;
    }

    /**
     * Sets the value of the inmemory property.
     * 
     */
    public void setInmemory(boolean value) {
        this.inmemory = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the database property.
     * 
     * @return
     *     possible object is
     *     {@link XMLLookup.Database }
     *     
     */
    public XMLLookup.Database getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLLookup.Database }
     *     
     */
    public void setDatabase(XMLLookup.Database value) {
        this.database = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link XMLLookup.File }
     *     
     */
    public XMLLookup.File getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLLookup.File }
     *     
     */
    public void setFile(XMLLookup.File value) {
        this.file = value;
    }

    /**
     * Gets the value of the keys property.
     * 
     * @return
     *     possible object is
     *     {@link XMLLookup.Keys }
     *     
     */
    public XMLLookup.Keys getKeys() {
        return keys;
    }

    /**
     * Sets the value of the keys property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLLookup.Keys }
     *     
     */
    public void setKeys(XMLLookup.Keys value) {
        this.keys = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link XMLLookup.Values }
     *     
     */
    public XMLLookup.Values getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLLookup.Values }
     *     
     */
    public void setValues(XMLLookup.Values value) {
        this.values = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="sql" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="loadall" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "url",
        "user",
        "password",
        "sql",
        "loadall"
    })
    public static class Database {

        @XmlElement(required = true)
        protected Object type;
        @XmlElement(required = true)
        protected Object url;
        @XmlElement(required = true)
        protected Object user;
        @XmlElement(required = true)
        protected Object password;
        @XmlElement(required = true)
        protected Object sql;
        @XmlElement(required = true)
        protected Object loadall;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setType(Object value) {
            this.type = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setUrl(Object value) {
            this.url = value;
        }

        /**
         * Gets the value of the user property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getUser() {
            return user;
        }

        /**
         * Sets the value of the user property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setUser(Object value) {
            this.user = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPassword() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPassword(Object value) {
            this.password = value;
        }

        /**
         * Gets the value of the sql property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getSql() {
            return sql;
        }

        /**
         * Sets the value of the sql property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setSql(Object value) {
            this.sql = value;
        }

        /**
         * Gets the value of the loadall property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getLoadall() {
            return loadall;
        }

        /**
         * Sets the value of the loadall property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setLoadall(Object value) {
            this.loadall = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="delimiter" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="quote" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "path",
        "delimiter",
        "quote"
    })
    public static class File {

        @XmlElement(required = true)
        protected Object path;
        @XmlElement(required = true)
        protected Object delimiter;
        @XmlElement(required = true)
        protected Object quote;

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPath(Object value) {
            this.path = value;
        }

        /**
         * Gets the value of the delimiter property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDelimiter() {
            return delimiter;
        }

        /**
         * Sets the value of the delimiter property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDelimiter(Object value) {
            this.delimiter = value;
        }

        /**
         * Gets the value of the quote property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getQuote() {
            return quote;
        }

        /**
         * Sets the value of the quote property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setQuote(Object value) {
            this.quote = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "field"
    })
    public static class Keys {

        @XmlElement(required = true)
        protected List<Object> field;

        /**
         * Gets the value of the field property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the field property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getField() {
            if (field == null) {
                field = new ArrayList<Object>();
            }
            return this.field;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="field" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "field"
    })
    public static class Values {

        @XmlElement(required = true)
        protected List<Object> field;

        /**
         * Gets the value of the field property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the field property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getField() {
            if (field == null) {
                field = new ArrayList<Object>();
            }
            return this.field;
        }

    }

}
